In [1]:
import numpy as np

In [2]:
matriks_13 = np.array([[[11,26,20,4]],[[6,11,20,10]],[[10,31,20,5]]])
print(matriks_13)

[[[11 26 20  4]]

 [[ 6 11 20 10]]

 [[10 31 20  5]]]


In [3]:
matriks_13.ndim

3

In [4]:
matriks_13.shape

(3, 1, 4)

In [5]:
matriks_13 = np.array([[11,26,20,4],[6,11,20,10]])
print(matriks_13)

[[11 26 20  4]
 [ 6 11 20 10]]


In [6]:
matriks_13.ndim

2

In [7]:
matriks_13.shape

(2, 4)

In [8]:
a_13 = np.array([[[4,7,9,2],[1,5,3,9]],[[2,3,6,5],[10,4,16,9]],[[3,19,5,8],[3,6,8,10]]])
print(a_13)

[[[ 4  7  9  2]
  [ 1  5  3  9]]

 [[ 2  3  6  5]
  [10  4 16  9]]

 [[ 3 19  5  8]
  [ 3  6  8 10]]]


In [9]:
a_13.shape

(3, 2, 4)

In [10]:
a_13.ndim

3

In [11]:
matrix_13 = np.array([[2,4,6,8],[1,3,5,7],[2,5,8,1]])
print(matrix_13)

[[2 4 6 8]
 [1 3 5 7]
 [2 5 8 1]]


In [12]:
matrix_13[2,3]

1

In [13]:
matrix_13[2,:]

array([2, 5, 8, 1])

In [14]:
matrix_13[:,0]

array([2, 1, 2])

In [15]:
matrix_13[1,1:3]

array([3, 5])

In [16]:
matrix_13[0,0:2:1]

array([2, 4])

In [17]:
matrix_13[2,3] = 9
print(matrix_13)

[[2 4 6 8]
 [1 3 5 7]
 [2 5 8 9]]


In [18]:
matriks_satu_13 = np.ones((4, 3))
print("Matriks Satu:")
print(matriks_satu_13)

Matriks Satu:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
matriks_custom_13 = np.full((3, 3),5)
print("Matriks Custom Angka:")
print(matriks_custom_13)

Matriks Custom Angka:
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [20]:
matriks_zero_13 = np.zeros((3, 3))
print("Matriks Nol:")
print(matriks_zero_13)

Matriks Nol:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
matriks_identitas_13= np.eye(3)
print("Matriks Identitas:")
print(matriks_identitas_13)

Matriks Identitas:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
matriks_random_13 = np.random.rand(2,2)
print("Matriks Acak:")
print(matriks_random_13)

Matriks Acak:
[[0.24746985 0.50622512]
 [0.06251394 0.96051448]]


In [23]:
matriks_random_13 = np.random.randint(1,20, size = (3,5))
print("Matriks Acak:")
print(matriks_random_13)

Matriks Acak:
[[10 11 15  4 18]
 [ 2 11 15  8 12]
 [17 16 15 19  6]]


In [24]:
diagonal_13 = [1,2,3,4]
matriks_diagonal_13 = np.diag(diagonal_13)
print("Matriks Diagonal:")
print(matriks_diagonal_13)

Matriks Diagonal:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [25]:
matriks_segitiga_atas_13 = np.triu([[1, 2, 3],
                                    [4, 5, 6],
                                    [7, 8, 9]])
print("Matriks Segitiga Atas:")
print(matriks_segitiga_atas_13)

Matriks Segitiga Atas:
[[1 2 3]
 [0 5 6]
 [0 0 9]]


In [26]:
matriks_segitiga_bawah_13 = np.tril([[1, 2, 3],
                                     [4, 5, 6],
                                     [7, 8, 9]])
print("Matriks Segitiga Bawah:")
print(matriks_segitiga_bawah_13)

Matriks Segitiga Bawah:
[[1 0 0]
 [4 5 0]
 [7 8 9]]


In [27]:
matriks_persegi_13 = np.array([[1, 2, 3, 4],
                               [5, 6, 7, 8],
                               [9, 10, 11, 12],
                               [13, 14, 15, 16]])
print("Matriks Persegi:")
print(matriks_persegi_13)

Matriks Persegi:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [28]:
a_13 = np.array([3,4,6,1,5])
print(a_13)

[3 4 6 1 5]


In [29]:
b_13 = a_13
print(b_13)

[3 4 6 1 5]


In [30]:
b_13[3] = 10
print(b_13)

[ 3  4  6 10  5]


In [31]:
print(a_13)

[ 3  4  6 10  5]


In [32]:
x_13 = np.array([11,12,13,16,15])
print(x_13)

[11 12 13 16 15]


In [33]:
y_13 = x_13.copy()
print(y_13)

[11 12 13 16 15]


In [34]:
y_13[3]=14
print(y_13)

[11 12 13 14 15]


In [35]:
print(x_13)

[11 12 13 16 15]


In [36]:
matriks1_13 = np.array([2,4,6,8])
print(matriks1_13)


[2 4 6 8]


In [37]:
matriks1_13 + 3

array([ 5,  7,  9, 11])

In [38]:
matriks1_13 - 5

array([-3, -1,  1,  3])

In [39]:
matriks1_13 * 4

array([ 8, 16, 24, 32])

In [40]:
matriks1_13 / 4

array([0.5, 1. , 1.5, 2. ])

In [41]:
matriks1_13 ** 2

array([ 4, 16, 36, 64])

In [42]:
matriks2_13 = np.array([3,6,9,12])
print(matriks2_13)

[ 3  6  9 12]


In [43]:
matriks1_13 + matriks2_13

array([ 5, 10, 15, 20])

In [44]:
matriks2_13 - matriks1_13

array([1, 2, 3, 4])

In [45]:
matriks1_13 * matriks2_13

array([ 6, 24, 54, 96])

In [46]:
matriks2_13 / matriks1_13

array([1.5, 1.5, 1.5, 1.5])

In [47]:
matriks2_13 ** matriks1_13

array([        9,      1296,    531441, 429981696])

In [48]:
matriks_13 = np.array([-1,0,1])
print(matriks_13)

[-1  0  1]


In [49]:
np.cos(matriks_13)

array([0.54030231, 1.        , 0.54030231])

In [50]:
np.sin(matriks_13)

array([-0.84147098,  0.        ,  0.84147098])

In [51]:
np.tan(matriks_13)

array([-1.55740772,  0.        ,  1.55740772])

In [52]:
np.cosh(matriks_13)

array([1.54308063, 1.        , 1.54308063])

In [53]:
np.sinh(matriks_13)

array([-1.17520119,  0.        ,  1.17520119])

In [54]:
np.tanh(matriks_13)

array([-0.76159416,  0.        ,  0.76159416])

In [55]:
matriks1_13 = np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])
matriks2_13= np.array([[10, 11, 12],
                       [13, 14, 15],
                       [16, 17, 18]])

hasil_13 = matriks1_13 + matriks2_13

print("Hasil Penjumlahan:")
print(hasil_13)

Hasil Penjumlahan:
[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [56]:
matriks1_13 = np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])
matriks2_13= np.array([[10, 11, 12],
                       [13, 14, 15],
                       [16, 17, 18]])

hasil_13 = matriks2_13 - matriks1_13

print("Hasil Pengurangan:")
print(hasil_13)

Hasil Pengurangan:
[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [57]:
matriks1_13 = np.array([[9,8,7],
                        [1,2,3],
                        [5,4,6]])
matriks2_13 = np.array([[1,3,5],
                        [2,6,0],
                        [9,6,3]])

hasil_13 = matriks1_13 * matriks2_13

print("Hasil Perkalian:")
print(hasil_13)

Hasil Perkalian:
[[ 9 24 35]
 [ 2 12  0]
 [45 24 18]]


In [58]:
matriks1_13 = np.array([[4, 6, 8],
                        [10, 12, 14],
                        [16, 18, 20]])
matriks2_13 = np.array([[2, 3, 4],
                        [5, 6, 7],
                        [8, 9, 10]])

hasil_13 = matriks1_13 / matriks2_13

print("Hasil Pembagian:")
print(hasil_13)

Hasil Pembagian:
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [59]:
matriks_13 = np.array([[2, 3, 4],
                       [5, 6, 7],
                       [8, 9, 10]])

hasil_13 = matriks_13 ** 2
print("Hasil Pangkat:")
print(hasil_13)

Hasil Pangkat:
[[  4   9  16]
 [ 25  36  49]
 [ 64  81 100]]


In [60]:
matriks_13 = np.array([[4, 9, 16],
                       [25, 36, 49],
                       [64, 81, 100]])
hasil_13 = np.sqrt(matriks_13)
print("Hasil Akar:")
print(hasil_13)

Hasil Akar:
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]


In [61]:
a_13 = np.array([[4,8,12,16],[1,3,5,7]])
print(a_13)

[[ 4  8 12 16]
 [ 1  3  5  7]]


In [62]:
b_13 = np.array([[1,4,2,5],[3,4,5,6]])
print(b_13)

[[1 4 2 5]
 [3 4 5 6]]


In [63]:
c_13 = a_13 * b_13
print (c_13)

[[ 4 32 24 80]
 [ 3 12 25 42]]


In [64]:
x_13 = np.array([[2,6],[5,1],[8,9],[5,2]])
print(x_13)

[[2 6]
 [5 1]
 [8 9]
 [5 2]]


In [65]:
y_13 = np.matmul(a_13,x_13)
print(y_13)

[[224 172]
 [ 92  68]]


In [66]:
matriksx_13 = np.array([[1, 2, 3],
                        [4, 5, 6]])

matriksy_13 = np.array([[10, 11],
                        [13, 14],
                        [16, 17]])

hasil_13 = np.matmul(matriksx_13, matriksy_13)

print("Hasil Perkalian Matriks:")
print(hasil_13)

Hasil Perkalian Matriks:
[[ 84  90]
 [201 216]]


In [67]:
matriks_13 = np.array([[1,4,8,12],
                       [0,2,5,9],
                       [10,5,0,-4]])
print(matriks_13)

[[ 1  4  8 12]
 [ 0  2  5  9]
 [10  5  0 -4]]


In [68]:
min_matriks_13 = np.min(matriks_13)
print(min_matriks_13)

-4


In [69]:
min_matriks_13 = np.min(matriks_13,axis = 0)
print(min_matriks_13)

[ 0  2  0 -4]


In [70]:
min_matriks_13 = np.min(matriks_13,axis = 1)
print(min_matriks_13)

[ 1  0 -4]


In [71]:
max_matriks_13 = np.max(matriks_13)
print(max_matriks_13)

12


In [72]:
max_matriks_13 = np.max(matriks_13,axis = 0)
print(max_matriks_13)

[10  5  8 12]


In [73]:
max_matriks_13 = np.max(matriks_13,axis = 1)
print(max_matriks_13)

[12  9 10]


In [74]:
sum_matriks_13 = np.sum(matriks_13)
print(sum_matriks_13)

52


In [75]:
sum_matriks_13 = np.sum(matriks_13,axis = 0)
print(sum_matriks_13)

[11 11 13 17]


In [76]:
sum_matriks_13 = np.sum(matriks_13,axis = 1)
print(sum_matriks_13)

[25 16 11]


In [77]:
matriks_13 = np.array([[10,4,8,3],
                       [2,6,1,9],
                       [4,0,1,5]])

nilai_min_13 = np.min(matriks_13)
min_kolom_13 = np.min(matriks_13, axis=0)
min_baris_13 = np.min(matriks_13, axis=1)


nilai_max_13 = np.max(matriks_13)
max_kolom_13 = np.max(matriks_13, axis=0)
max_baris_13 = np.max(matriks_13, axis=1)

nilai_sum_13 = np.sum(matriks_13)
sum_kolom_13 = np.sum(matriks_13, axis=0)
sum_baris_13 = np.sum(matriks_13, axis=1)

print("Nilai minimum:", nilai_min_13)
print("Nilai minimum per kolom:", min_kolom_13)
print("Nilai minimum per baris:", min_baris_13)

print("Nilai maksimum:", nilai_max_13)
print("Nilai maksimum per kolom:", max_kolom_13)
print("Nilai maksimum per baris:", max_baris_13)

print("Jumlah:", nilai_sum_13)
print("Jumlah per kolom:", sum_kolom_13)
print("Jumlah per baris:", sum_baris_13)

Nilai minimum: 0
Nilai minimum per kolom: [2 0 1 3]
Nilai minimum per baris: [3 1 0]
Nilai maksimum: 10
Nilai maksimum per kolom: [10  6  8  9]
Nilai maksimum per baris: [10  9  5]
Jumlah: 53
Jumlah per kolom: [16 10 10 17]
Jumlah per baris: [25 18 10]
